# Generated by Django 4.0.5 on 2022-06-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinosTuristicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinoturistico',
            name='nombreCiudad',
            field=models.TextField(),
        ),
    ]
